const express = require('express');
const router = express.Router();
const { checkIn, checkOut, getAttendance, getTodayAttendance } = require('../controllers/attendanceController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.post('/checkin', checkIn);
router.post('/checkout', checkOut);
router.get('/', getAttendance);
router.get('/today', getTodayAttendance);
module.exports = router;
